apiVersion: apps/v1
kind: Deployment
metadata:
  name: vortoapp
spec:
  selector:
    matchLabels:
      app: vortoms
  replicas: 1
  template:
    metadata:
      labels:
        app: vortoms
    spec:
      containers:
      - name: vortoms
        image: nimboya/vortotest:latest
        ports:
        - containerPort: 8081
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: vorto-svc
spec:
  selector:
    app: myappms
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8081
  type: LoadBalancer
